registration for strategies and configuration participants
polevgart/economics_ai_python_game pull request #11
Opened 2023-01-14 13:23 UTC by polevgart

2023-01-14 21:18 UTC, KingAArtur commented on main_play.py
> +                named_strategy.player_namse = player_name
`player_namse` typo

2023-01-15 10:58 UTC, KingAArtur commented
I have checked this out and it seems to be ok but idk i wanna **MATHEMATICIAN** to look at it

2023-01-15 15:14 UTC, Mathematician2000 requested changes

2023-01-15 15:14 UTC, Mathematician2000 commented on strategies/registration/__init__.py
> +    def registry(self, participant: type):
register?

2023-01-15 15:14 UTC, Mathematician2000 commented on strategies/registration/__init__.py
> +def registry_strategy(strategy_cls):
register?

2023-01-16 06:57 UTC, polevgart commented on strategies/registration/__init__.py
> +def registry_strategy(strategy_cls):
ok

2023-01-16 06:57 UTC, polevgart commented on strategies/registration/__init__.py
> +    def registry(self, participant: type):
ok

2023-01-17 07:56 UTC, Mathematician2000 approved these changes

2023-01-17 07:56 UTC, merged